version: 0.2

env:
  shell: /bin/bash
  parameter-store:
    DOCKERHUB_PASSWORD: /prod/sharedInfrastructure/dockerhub/password
    DOCKERHUB_USERNAME: /prod/sharedInfrastructure/dockerhub/username
  variables:
    DOCKER_CLI_EXPERIMENTAL: enabled

batch:
  fast-fail: true
  build-graph:
    - identifier: amd64
      env:
        compute-type: BUILD_GENERAL1_MEDIUM
        privileged-mode: true
        variables:
          platforms: linux/amd64
          ARCH: amd64
          tag_suffix: -amd64
      buildspec: buildspec-platform.yml

    - identifier: arm64
      env:
        type: ARM_CONTAINER
        image: aws/codebuild/amazonlinux2-aarch64-standard:3.0-24.06.07
        compute-type: BUILD_GENERAL1_MEDIUM
        privileged-mode: true
        variables:
          platforms: linux/arm64
          ARCH: arm64
          tag_suffix: -arm64
      buildspec: buildspec-platform.yml

    - identifier: manifest
      env:
        compute-type: BUILD_GENERAL1_MEDIUM
        privileged-mode: true
      depend-on:
        - amd64
        - arm64

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
  build:
    commands:
      - IMAGE=joltdesign/php
      - |
          echo Creating manifests...

          for VERSION in "8.2" "8.3" "8.4"; do
            for RUNTIME in "" "-apache"; do
              for SUFFIX in "" "-dev"; do
                TAG=${IMAGE}:${VERSION}${RUNTIME}${SUFFIX}

                echo "Creating manifest for $TAG"

                docker manifest create $TAG \
                  ${TAG}-amd64 \
                  ${TAG}-arm64

                docker manifest push $TAG
              done
            done
          done
    finally:
      - rm -rfv ~/.docker
  post_build:
    commands:
      - echo Build completed at `date`
