version: 0.2

env:
  secrets-manager:
    DOCKERHUB_PASSWORD: dockerhub/password
    DOCKERHUB_USERNAME: dockerhub/username

phases:
  install:
    commands:
      - export BUILDX_VERSION=$(curl --silent "https://api.github.com/repos/docker/buildx/releases/latest" | jq -r .tag_name)
      - curl -JLO "https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.linux-${ARCH:-amd64}"
      - mkdir -p ~/.docker/cli-plugins
      - mv "buildx-$BUILDX_VERSION.linux-${ARCH:-amd64}" ~/.docker/cli-plugins/docker-buildx
      - chmod +x ~/.docker/cli-plugins/docker-buildx
      - docker run --privileged --rm tonistiigi/binfmt --install ${ARCH:-amd64}
      - docker buildx create --name container-builder --driver docker-container --use --bootstrap
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
  build:
    commands:
      - echo "Build started on `date` ($(git rev-parse HEAD | cut -c -8))"
      - echo Building the Docker image...
      - docker buildx bake --builder=container-builder --progress=plain --push
  post_build:
    commands:
      - echo Build completed at `date`
