name: ci

on:
  workflow_dispatch:
  schedule:
    # run every day at 4:20
    - cron: '20 4 * * *'
  push:
    branches: [master]

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read PHP versions
        id: versions
        run: echo "versions=$(jq -r '.[\"php-versions\"] | join(",")' versions.json)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/bake-action@v6
        env:
          PHP_VERSIONS: ${{ steps.versions.outputs.versions }}
        with:
          push: true
